<?php
/**
 * CustomersApi
 * PHP version 5
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.client;

use \com.volocommerce.api.v1.sdk.invoker\ApiClient;
use \com.volocommerce.api.v1.sdk.invoker\ApiException;
use \com.volocommerce.api.v1.sdk.invoker\Configuration;
use \com.volocommerce.api.v1.sdk.invoker\ObjectSerializer;

/**
 * CustomersApi Class Doc Comment
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomersApi
{
    /**
     * API Client
     *
     * @var \com.volocommerce.api.v1.sdk.invoker\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \com.volocommerce.api.v1.sdk.invoker\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\com.volocommerce.api.v1.sdk.invoker\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \com.volocommerce.api.v1.sdk.invoker\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \com.volocommerce.api.v1.sdk.invoker\ApiClient $apiClient set the API client
     *
     * @return CustomersApi
     */
    public function setApiClient(\com.volocommerce.api.v1.sdk.invoker\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation doUpdate
     *
     * Update Customer
     *
     * @param \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\UpdateCustomer $body  (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return void
     */
    public function doUpdate($body = null)
    {
        list($response) = $this->doUpdateWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation doUpdateWithHttpInfo
     *
     * Update Customer
     *
     * @param \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\UpdateCustomer $body  (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function doUpdateWithHttpInfo($body = null)
    {
        // parse inputs
        $resourcePath = "/customers";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json; charset=utf-8']);

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/customers'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation getCustomers
     *
     * Returns a list of customers
     *
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @param int $id Customer ID (optional)
     * @param string $name First name or last name of the customer (optional)
     * @param string $company_name Company Name (optional)
     * @param string $postcode Postcode of the address (optional)
     * @param string $email Email address of the customer (optional)
     * @param string $phone Phone number of the customer (optional)
     * @param string $merchant_type Merchant type of the customer (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponse
     */
    public function getCustomers($authorization, $x_api_key, $id = null, $name = null, $company_name = null, $postcode = null, $email = null, $phone = null, $merchant_type = null)
    {
        list($response) = $this->getCustomersWithHttpInfo($authorization, $x_api_key, $id, $name, $company_name, $postcode, $email, $phone, $merchant_type);
        return $response;
    }

    /**
     * Operation getCustomersWithHttpInfo
     *
     * Returns a list of customers
     *
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @param int $id Customer ID (optional)
     * @param string $name First name or last name of the customer (optional)
     * @param string $company_name Company Name (optional)
     * @param string $postcode Postcode of the address (optional)
     * @param string $email Email address of the customer (optional)
     * @param string $phone Phone number of the customer (optional)
     * @param string $merchant_type Merchant type of the customer (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return array of \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCustomersWithHttpInfo($authorization, $x_api_key, $id = null, $name = null, $company_name = null, $postcode = null, $email = null, $phone = null, $merchant_type = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling getCustomers');
        }
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $x_api_key when calling getCustomers');
        }
        // parse inputs
        $resourcePath = "/customers";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);

        // query params
        if ($id !== null) {
            $queryParams['id'] = $this->apiClient->getSerializer()->toQueryValue($id);
        }
        // query params
        if ($name !== null) {
            $queryParams['name'] = $this->apiClient->getSerializer()->toQueryValue($name);
        }
        // query params
        if ($company_name !== null) {
            $queryParams['companyName'] = $this->apiClient->getSerializer()->toQueryValue($company_name);
        }
        // query params
        if ($postcode !== null) {
            $queryParams['postcode'] = $this->apiClient->getSerializer()->toQueryValue($postcode);
        }
        // query params
        if ($email !== null) {
            $queryParams['email'] = $this->apiClient->getSerializer()->toQueryValue($email);
        }
        // query params
        if ($phone !== null) {
            $queryParams['phone'] = $this->apiClient->getSerializer()->toQueryValue($phone);
        }
        // query params
        if ($merchant_type !== null) {
            $queryParams['merchantType'] = $this->apiClient->getSerializer()->toQueryValue($merchant_type);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // header params
        if ($x_api_key !== null) {
            $headerParams['x-api-key'] = $this->apiClient->getSerializer()->toHeaderValue($x_api_key);
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponse',
                '/customers'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\VoloAPIErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation removeCustomer
     *
     * Delete the customer
     *
     * @param int $customer_id Customer id (required)
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\DeleteCustomerResponse
     */
    public function removeCustomer($customer_id, $authorization, $x_api_key)
    {
        list($response) = $this->removeCustomerWithHttpInfo($customer_id, $authorization, $x_api_key);
        return $response;
    }

    /**
     * Operation removeCustomerWithHttpInfo
     *
     * Delete the customer
     *
     * @param int $customer_id Customer id (required)
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return array of \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\DeleteCustomerResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeCustomerWithHttpInfo($customer_id, $authorization, $x_api_key)
    {
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling removeCustomer');
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling removeCustomer');
        }
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $x_api_key when calling removeCustomer');
        }
        // parse inputs
        $resourcePath = "/customers/{customerId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json; charset=utf-8']);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // header params
        if ($x_api_key !== null) {
            $headerParams['x-api-key'] = $this->apiClient->getSerializer()->toHeaderValue($x_api_key);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\DeleteCustomerResponse',
                '/customers/{customerId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\DeleteCustomerResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\DeleteCustomerResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\VoloAPIErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation saveCustomers
     *
     * Add a list of customers
     *
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @param \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\AddCustomers $body  (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponseBeanList
     */
    public function saveCustomers($authorization, $x_api_key, $body = null)
    {
        list($response) = $this->saveCustomersWithHttpInfo($authorization, $x_api_key, $body);
        return $response;
    }

    /**
     * Operation saveCustomersWithHttpInfo
     *
     * Add a list of customers
     *
     * @param string $authorization Auth token (required)
     * @param string $x_api_key API Key (required)
     * @param \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\AddCustomers $body  (optional)
     * @throws \com.volocommerce.api.v1.sdk.invoker\ApiException on non-2xx response
     * @return array of \com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponseBeanList, HTTP status code, HTTP response headers (array of strings)
     */
    public function saveCustomersWithHttpInfo($authorization, $x_api_key, $body = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling saveCustomers');
        }
        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $x_api_key when calling saveCustomers');
        }
        // parse inputs
        $resourcePath = "/customers";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json; charset=utf-8']);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // header params
        if ($x_api_key !== null) {
            $headerParams['x-api-key'] = $this->apiClient->getSerializer()->toHeaderValue($x_api_key);
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponseBeanList',
                '/customers'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponseBeanList', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\CustomerResponseBeanList', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\com.volocommerce.api.v1.sdk.invoker\com.volocommerce.api.v1.sdk.model\VoloAPIErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
