<?php
/**
 * PurchaseOrdersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace com.volocommerce.api.v1.sdk.invoker;

use \com.volocommerce.api.v1.sdk.invoker\Configuration;
use \com.volocommerce.api.v1.sdk.invoker\ApiClient;
use \com.volocommerce.api.v1.sdk.invoker\ApiException;
use \com.volocommerce.api.v1.sdk.invoker\ObjectSerializer;

/**
 * PurchaseOrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PurchaseOrdersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for confirmDelivery
     *
     * Confirm Delivery..
     *
     */
    public function testConfirmDelivery()
    {
    }

    /**
     * Test case for confirmOrder
     *
     * Confirm Purchase Order..
     *
     */
    public function testConfirmOrder()
    {
    }

    /**
     * Test case for doUpdate
     *
     * Update Purchase Order..
     *
     */
    public function testDoUpdate()
    {
    }

    /**
     * Test case for getDetails
     *
     * Get Purchase Order Details.
     *
     */
    public function testGetDetails()
    {
    }

    /**
     * Test case for removePurchaseOrder
     *
     * Remove Purchase Order.
     *
     */
    public function testRemovePurchaseOrder()
    {
    }

    /**
     * Test case for removePurchaseOrderItems
     *
     * Remove Purchase Order Item.
     *
     */
    public function testRemovePurchaseOrderItems()
    {
    }

    /**
     * Test case for savePurchaseOrders
     *
     * Add a list of Purchase Order.
     *
     */
    public function testSavePurchaseOrders()
    {
    }

    /**
     * Test case for updateDeliveries
     *
     * Update deliveries..
     *
     */
    public function testUpdateDeliveries()
    {
    }
}
