<?php
/**
 * SuppliersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace com.volocommerce.api.v1.sdk.invoker;

use \com.volocommerce.api.v1.sdk.invoker\Configuration;
use \com.volocommerce.api.v1.sdk.invoker\ApiClient;
use \com.volocommerce.api.v1.sdk.invoker\ApiException;
use \com.volocommerce.api.v1.sdk.invoker\ObjectSerializer;

/**
 * SuppliersApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.volocommerce.api.v1.sdk.invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SuppliersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for doUpdate
     *
     * Update Supplier.
     *
     */
    public function testDoUpdate()
    {
    }

    /**
     * Test case for getSuppliers
     *
     * Returns a list of suppliers.
     *
     */
    public function testGetSuppliers()
    {
    }

    /**
     * Test case for removeSupplier
     *
     * Delete the supplier.
     *
     */
    public function testRemoveSupplier()
    {
    }

    /**
     * Test case for saveSupplier
     *
     * Add a list of suppliers.
     *
     */
    public function testSaveSupplier()
    {
    }
}
